Some useful links from Dana:

https://scikit-image.org/docs/stable/auto_examples/edges/plot_skeleton.html

https://nalinc.github.io/blog/2018/skin-detection-python-opencv/

https://docs.opencv.org/4.x/d9/d61/tutorial_py_morphological_ops.html

The paper and video we're basing everythign off of:

https://link.springer.com/article/10.1007/s11042-013-1501-1

https://www.youtube.com/watch?v=xML2S6bvMwI

In [2]:
import numpy as np
import math
import cv2
cap = cv2.VideoCapture(1)

# skin colour numbers
y_min = 64
y_max = 193
cr_min = 139 # 133
cr_max = 173
cb_min = 77
cb_max = 127

fire_ready = False
bullets = []
next_bullet = None
bullet_speed = 6
exit_angle = None
start_game = False


# get the angle between ab and ac given a, b, c xy-points of a triangle
# uses the law of cosines aka the cosine rule / formula
def cos_rule(a, b, c):
    # euclidian distance between points
    ab = math.dist(a, b)
    bc = math.dist(b, c)
    ac = math.dist(a, c)

    # using law of cosines to compute angle between ab and bc
    angle_abac = math.degrees(math.acos((ab ** 2 + ac ** 2 - bc ** 2) / (2 * ab * ac)))
    return angle_abac


while 1:
    _ret, img = cap.read()
    #cv2.rectangle(img, (700, 700), (100, 100), (0, 255, 0), 0)
    crop_img = img#img[100:700, 100:700]
    drawing = np.zeros(crop_img.shape, np.uint8)
    #grey = cv2.cvtColor(crop_img, cv2.COLOR_BGR2GRAY)
    kernel_size = (35, 35)
    
    img_ycrcb = cv2.cvtColor(crop_img, cv2.COLOR_BGR2YCrCb)
    #blurred = cv2.GaussianBlur(grey, kernel_size, 0)
    blurred = cv2.GaussianBlur(img_ycrcb, kernel_size, 0)

    scale_factor = 4
    if scale_factor != 1:
        blurred = cv2.resize(blurred, [blurred.shape[1]//scale_factor, blurred.shape[0]//scale_factor], interpolation=cv2.INTER_AREA)
    
    # skin color segmentation
    skin_ycrcb_mint = np.array([y_min, cr_min, cb_min], np.uint8)
    skin_ycrcb_maxt = np.array([y_max, cr_max, cb_max], np.uint8)
    thresholded = cv2.inRange(blurred, skin_ycrcb_mint, skin_ycrcb_maxt)
    #_ret, thresholded = cv2.threshold(blurred, 127, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
    contours, _hierarchy = cv2.findContours(thresholded.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)
    #contours, _hierarchy = cv2.findContours(thresholded.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_NONE)

    # if no contours are detected, don't draw anything
    if len(contours) != 0:
        # this is the largest contour found, which helps eliminate noise and should be the hand
        count1 = max(contours, key=lambda x: cv2.contourArea(x))

        # drawing the biggest enclosing circle of the contour shape, used for gesture recognition
        big_c, big_r = cv2.minEnclosingCircle(count1)
        big_c = (int(big_c[0])*scale_factor, int(big_c[1])*scale_factor)

        #if ((big_r*scale_factor) > (3.5* center_dist*scale_factor)):
        # center point
        cv2.circle(crop_img, big_c, 1, (0, 0, 255), 2)
        # circle containing hand
        cv2.circle(crop_img, big_c, int(big_r)*scale_factor, (0, 0, 255), 2)
            
        x, y, w, h = cv2.boundingRect(count1)

        # finding the palm center
        center_pt = (0, 0)
        center_dist = 0
        for pt_x in range(x, x+w, 2):
            for pt_y in range(y, y+h, 2):
                pt = (pt_x, pt_y)
                dist = cv2.pointPolygonTest(count1, pt, measureDist=True)
                if dist > center_dist:
                    center_pt = (pt_x * scale_factor, pt_y * scale_factor)
                    center_dist = dist
                #cv2.circle(crop_img, pt, 1, (255, 0, 255), 1)
                #else:
                #    cv2.circle(crop_img, pt, 1, (0, 0, 0), 1)
        # biggest circle in palm
        cv2.circle(crop_img, center_pt, int(center_dist)*scale_factor, (255, 0, 0), 2)
        # circle 3.5 * the radius
        #cv2.circle(crop_img, center_pt, int(center_dist*3.5)*scale_factor, (255, 255, 0), 2)
        # biggest circle / 2
        cv2.circle(crop_img, center_pt, int(center_dist//2)*scale_factor, (0, 165, 255), 2)
        # center of biggest circle
        cv2.circle(crop_img, center_pt, 1, (255, 0, 0), 2)

        # not necessary at the moment
        # rotRect = cv2.minAreaRect(count1)
        # box = cv2.boxPoints(rotRect)
        # box = np.int64(box)
        # cv2.drawContours(crop_img, [box*scale_factor], 0, (255, 255, 0), 1)

        #cv2.rectangle(crop_img, (x*scale_factor, y*scale_factor), ((x + w)*scale_factor, (y + h)*scale_factor), (0, 0, 255), 1)

        hull = cv2.convexHull(count1)
        cv2.drawContours(drawing, [count1*scale_factor], 0, (0, 255, 0), 0)
        cv2.drawContours(drawing, [hull*scale_factor], 0, (0, 0, 255), 0)
        try:
            hull = cv2.convexHull(count1, returnPoints=False)
            defects = cv2.convexityDefects(count1, hull)
        except:
            print(hull, count1)
            continue
            raise IOError("Hull issue")
        count_defects = 0
        cv2.drawContours(thresholded, contours*scale_factor, -1, (0, 255, 0), 3)
        

        # doing contour extractions once again within the 3.5x circle
        # grey = cv2.cvtColor(crop_img, cv2.COLOR_BGR2GRAY)
        # blurred2 = cv2.GaussianBlur(grey, kernel_size, 0)
        # _ret, thresholded2 = cv2.threshold(blurred2, 127, 255, cv2.THRESH_BINARY_INV + cv2.THRESH_OTSU)
        # contours2, _hierarchy = cv2.findContours(thresholded2.copy(), cv2.RETR_TREE, cv2.CHAIN_APPROX_SIMPLE)#cv2.CHAIN_APPROX_NONE)

        # if len(contours2) != 0:
        #     count1_2 = max(contours2, key=lambda x: cv2.contourArea(x))


        # print(len(contours), defects.shape, '\n\n', contours)
        # break

        # go through all the defects in the hull
        if defects is not None:
            finger_tips = []
            finger_valleys = []
            angles = []
            thumb_defect = None
            biggest_angle = 0
            for defect in defects:
                # start index, end index, farthest pt index, depth
                s, e, f, d = defect[0]
                start = tuple(count1[s][0])
                end = tuple(count1[e][0])
                far = tuple(count1[f][0])

                # depth has 8 fractional bits, to get the value as a float divide by 256
                depth = d // 256

                angle = cos_rule(far, start, end)

                # cosidered a finger when the angle is < 90º and depth of defect is between the small and large radius
                if angle <= 100 and depth > center_dist and depth < big_r:
                    count_defects += 1
                    finger_tips.append([s, e, f])
                    angles.append(angle)
                    max(contours, key=lambda x: cv2.contourArea(x))

                    if angle > biggest_angle:
                        biggest_angle = angle
                        thumb_defect = [start, end, far]

                    cv2.circle(crop_img, (start[0]*scale_factor, start[1]*scale_factor), 3, [255, 0, 255], 3)
                    cv2.circle(crop_img, (end[0]*scale_factor, end[1]*scale_factor), 3, [255, 0, 255], 3)
                    cv2.circle(crop_img, (far[0]*scale_factor, far[1]*scale_factor), 3, [255, 0, 255], 3)
                    #print(f"defect {count_defects}: start: {start}, end: {end}, far: {far}, ra: {int(center_dist)}, l: {depth}, rb: {int(big_r)}")

                cv2.line(crop_img, (start[0]*scale_factor, start[1]*scale_factor), (end[0]*scale_factor, end[1]*scale_factor), [0, 255, 0], 2)

            # for a in range(len(angles)):
            biggest_area = 0
            thumb = None

            for finger_tip in finger_tips:
                s, e, f = finger_tip
                area = cv2.contourArea(count1[s:e+1])
                if area > biggest_area:
                    biggest_area = area
                    thumb = finger_tip
                #biggest_area = max(finger_tips, key=lambda x: cv2.contourArea(count1[x[0]:x[1]+1]))
            
            if thumb is not None and start_game:
                s, e, f = thumb
                count1_reshaped = count1.reshape(-1, 2)

                cv2.fillPoly(crop_img, [count1_reshaped[s:e+1]*scale_factor], (255, 0, 0, 0.2))
                
                start = count1[s][0]
                end = count1[e][0]
                far = count1[f][0]
                angle = cos_rule(far, start, end)

                tip_1 = math.dist(start, far)
                tip_2 = math.dist(end, far)

                if (tip_1 > tip_2):
                    pointer_tip = start
                else:
                    pointer_tip = end

                cv2.line(crop_img, pointer_tip*scale_factor, far*scale_factor, (0, 0, 255), 6)

                # if angle < 80:
                #     fire_ready = False
                # else:
                cv2.putText(img, f"angle: {angle:3.0f} - aim", (50, 150), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 0), 2)
                fire_ready = True
                next_bullet = pointer_tip

                x_dist = pointer_tip[0] - far[0]
                y_dist = pointer_tip[1] - far[1]
                exit_angle = math.atan2(y_dist, x_dist)

        if fire_ready and count_defects == 0:
            cv2.putText(img, f"Fire!", (50, 250), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 0), 2)
            fire_ready = False

            if next_bullet is not None:
                bullets.append([next_bullet, exit_angle])

                next_x = next_bullet[0] + math.cos(exit_angle) * bullet_speed
                next_y = next_bullet[1] + math.sin(exit_angle) * bullet_speed
                next_coords = (next_x, next_y)
                #print(f"bullet_coords: {next_bullet}, angle: {math.degrees(exit_angle)}, next_coords: {next_coords}")

        if count_defects < 5:
            cv2.putText(img, f"{count_defects+1} finger(s)", (50, 50), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 0), 2)

        if count_defects == 4:
            start_game = True

    new_bullets = []
    for b in range(len(bullets)):
        bullet_coord, bullet_angle = bullets[b]

        # get rid of any bullets not within the screen
        if bullet_coord[0] > 0 and bullet_coord[0] < crop_img.shape[1] and bullet_coord[1] > 0 and bullet_coord[1] < crop_img.shape[0]:
            cv2.circle(crop_img, bullet_coord*scale_factor, 5, (255, 255, 120), 3)
            cv2.circle(drawing, bullet_coord*scale_factor, 5, (255, 255, 120), 3)

            # update the bullet location for the next frame
            bullet_coord[0] += math.cos(bullet_angle) * bullet_speed
            bullet_coord[1] += math.sin(bullet_angle) * bullet_speed
            new_bullets.append([bullet_coord, bullet_angle])

    bullets = new_bullets

    
    if start_game:
        cv2.putText(img, "game started", (50, 1000), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 180, 0), 2)
    else:
        cv2.putText(img, "waiting", (50, 1000), cv2.FONT_HERSHEY_SIMPLEX, 2, (0, 0, 180), 2)

    #cv2.imshow('main window', img)
    all_img = np.hstack((drawing, crop_img))
    cv2.imshow('Contours', all_img)
    #print('\n')
    #input()

    k = cv2.waitKey(1)
    if k == 27:
        break

cv2.destroyAllWindows()
cv2.waitKey(1)
cap.release()

[[ 81]
 [ 80]
 [ 75]
 [ 59]
 [ 57]
 [ 29]
 [ 18]
 [ 19]
 [  0]
 [113]
 [ 88]] [[[429 153]]

 [[427 155]]

 [[427 159]]

 [[424 162]]

 [[424 164]]

 [[422 166]]

 [[420 164]]

 [[418 164]]

 [[416 162]]

 [[414 162]]

 [[413 161]]

 [[412 161]]

 [[409 164]]

 [[408 164]]

 [[407 165]]

 [[405 165]]

 [[404 164]]

 [[401 164]]

 [[400 165]]

 [[401 164]]

 [[402 164]]

 [[403 165]]

 [[403 169]]

 [[402 170]]

 [[402 171]]

 [[399 174]]

 [[399 175]]

 [[398 176]]

 [[398 178]]

 [[394 182]]

 [[394 189]]

 [[395 190]]

 [[394 191]]

 [[394 192]]

 [[393 193]]

 [[393 198]]

 [[394 199]]

 [[393 200]]

 [[393 201]]

 [[391 203]]

 [[391 206]]

 [[392 207]]

 [[392 210]]

 [[391 211]]

 [[391 215]]

 [[392 216]]

 [[392 217]]

 [[395 220]]

 [[395 221]]

 [[396 222]]

 [[396 229]]

 [[395 230]]

 [[395 232]]

 [[385 242]]

 [[386 243]]

 [[385 244]]

 [[382 244]]

 [[379 241]]

 [[380 242]]

 [[380 243]]

 [[383 246]]

 [[383 247]]

 [[384 248]]

 [[384 249]]

 [[386 251]]

 [[386 252]]